import ImageHoverOff from "./ImageHoverOff";
import InquirePrints from "./InquirePrints";
import Landscape from "./Landscape";

export default function Building() {
  return (
    <>
      <InquirePrints />
      <Landscape
        source="/dailycapture/building/collage-building-landscape.png"
        alt="collage Building"
      />
      <div
        className={`flex flex-col md:flex-row flex-wrap justify-center items-center  mt-[80px] 
        }  `}
      >
        <ImageHoverOff
          source="/dailycapture/building/4.jpg"
          sizeH={500}
          sizeW={500}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/building/5.jpg"
          sizeH={400}
          sizeW={400}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-0763.jpg"
          sizeH={400}
          sizeW={400}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-0988.jpg"
          sizeH={400}
          sizeW={400}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-1605.jpg"
          sizeH={400}
          sizeW={400}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-4162.jpg"
          sizeH={400}
          sizeW={400}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-4188.jpg"
          sizeH={400}
          sizeW={400}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-4579.jpg"
          sizeH={400}
          sizeW={400}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-9944.jpg"
          sizeH={400}
          sizeW={400}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-0007.jpg"
          sizeH={600}
          sizeW={600}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-0822.jpg"
          sizeH={400}
          sizeW={400}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-1390.jpg"
          sizeH={500}
          sizeW={500}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-1391.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-1392.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-1396.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-1477.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-1478.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-1479.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-1482.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-1506.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-1508.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-2592.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-2593.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-4573.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-4574.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-4580.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/building/IMG-4590.jpg"
          sizeH={400}
          sizeW={400}
        />
      </div>
    </>
  );
}
