import ImageHoverOff from "../ImageHoverOff";
import InquirePrints from "../InquirePrints";
import Landscape from "../Landscape";

export default function Beach() {
  return (
    <>
      <InquirePrints />
      <Landscape
        source="/dailycapture/beach/collage-beach-landscape.png"
        alt="collage Beach"
      />
      <div
        className={`flex flex-col md:flex-row flex-wrap justify-center items-center  mt-[80px] 
        }  `}
      >
        <ImageHoverOff
          source="/dailycapture/beach/1.jpg"
          sizeH={500}
          sizeW={500}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/beach/2.jpg"
          sizeH={400}
          sizeW={400}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/beach/3.jpg"
          sizeH={400}
          sizeW={400}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-0102.jpg"
          sizeH={400}
          sizeW={400}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-0106.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-0112.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-0485.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-0487.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-0490.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-0515.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-0640.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-1382.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-1383.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-1388.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-1714.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-2845.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-5320.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-5321.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-5322.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-5325.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-5326.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-5327.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-5328.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-5329.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7094.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7591.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7090.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7537.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7541.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7544.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7550.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7551.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7555.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7575.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7090.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7589.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7590.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7635.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7730.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7731.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7732.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7378.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7530.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/beach/IMG-7531.jpg"
          sizeH={400}
          sizeW={400}
        />
      </div>
    </>
  );
}
