import Image from "next/image";
import ImageHoverOff from "../ImageHoverOff";
import InquirePrints from "../InquirePrints";
import Landscape from "../Landscape";

export default function BlackWhite() {
  return (
    <>
      <InquirePrints />
      <Landscape
        source="/dailycapture/b&w/collage-byw-landscape.png"
        alt="collage b&w"
      />
      <div
        className={`flex flex-col md:flex-row flex-wrap justify-center items-center  mt-[80px] 
        }  `}
      >
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-0037.jpg"
          sizeH={500}
          sizeW={500}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-0227.jpg"
          sizeH={400}
          sizeW={400}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-0401.jpg"
          sizeH={600}
          sizeW={600}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-0481.jpg"
          sizeH={400}
          sizeW={400}
          className="mx-auto"
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1424.jpg"
          sizeH={500}
          sizeW={500}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1433.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1434.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1437.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1457.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1458.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1459.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1460.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1461.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1462.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1463.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1464.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1465.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1466.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1467.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1475.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1476.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1480.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-1514.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-3048.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-3049.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-3050.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-3051.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-3052.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-3351.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-5635.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-5643.jpg"
          sizeH={400}
          sizeW={400}
        />
        <ImageHoverOff
          source="/dailycapture/b&w/IMG-3579.jpg"
          sizeH={400}
          sizeW={400}
        />
      </div>
    </>
  );
}
